### PR TITLE
Add application monitoring section to documentation

### PR DESCRIPTION
**Pull request by marynaggita**
#### What does this PR do?

It adds the Application Monitoring metrics section to the documentation.

#### Screenshots

Screenshot from 2020-10-12 04-10-56

Screenshot from 2020-10-12 04-07-56

### CODE REVIEW

**Review by neelxie — APPROVED** [review]
@marynaggita Excellent work on this.

**Review by Mubangizi — CHANGES_REQUESTED** [review]
Great work @marynaggita ,
Although i think you need to crop those images that are being shown, for example crop out the browser tabs, then the logs image would look better it the white margin was also cropped out.

**Review by MutegekiHenry — COMMENTED** [review]
i agree with what @Mubangizi says about cropping

**Comment by neelxie** [comment]
> i agree with what @Mubangizi says about cropping

@Mubangizi @MutegekiHenry the requested changes have been worked on.

**Review by MutegekiHenry — APPROVED** [review]

**Review by Mubangizi — APPROVED** [review]

**Pull request merged**
