### PR TITLE
Update Database section

### PR DESCRIPTION
**Pull request by neelxie**
#### What does this PR do?
It updates the database section.

#### Ticket
https://trello.com/c/fWhJnEKo

#### Screenshots
Screenshot from 2021-05-04 18-26-02
Screenshot from 2021-05-04 18-26-17

### CODE REVIEW

**Comment by Mubangizi** [comment]
Hey @neelxie , this is great stuff. I have a small UI tweak that I would like to suggest on the flavour `dropdown`. Do you mind removing the black border, i feel its too  much on the feel of the page

**Comment by neelxie** [comment]
> Hey @neelxie , this is great stuff. I have a small UI tweak that I would like to suggest on the flavour `dropdown`. Do you mind removing the black border, i feel its too much on the feel of the page

@Mubangizi you do realize this is the DOCUMENTATION, I kindly request we raise issues of UI in the pre-defined avenues just for purposes of separation of concerns as it already is bro because what is documented is what is already on the UI!

**Review by Mubangizi — APPROVED** [review]
LGTM

**Review by MutegekiHenry — APPROVED** [review]
Looks good

**Pull request merged**
