### PR TITLE
Add medium blog articles link

### PR DESCRIPTION
**Pull request by neelxie**
#### What does this PR do?

Embed our medium blog articles link within our documentation.

### CODE REVIEW

**Review by MutegekiHenry — COMMENTED** [review]
@neelxie Thanks for this. I prefer it when you have a small description under the Medium Articles heading and in there that's where the link can be put. Just a line telling someone to find all the Cranecloud Medium articles via the CC Page and they can follow this link, followed by the link.

**Comment by neelxie** [comment]
> @neelxie Thanks for this. I prefer it when you have a small description under the Medium Articles heading and in there that's where the link can be put. Just a line telling someone to find all the Cranecloud Medium articles via the CC Page and they can follow this link, followed by the link.

@MutegekiHenry thank you for the feedback let me work on that ASAP!

**Comment by neelxie** [comment]
> > @neelxie Thanks for this. I prefer it when you have a small description under the Medium Articles heading and in there that's where the link can be put. Just a line telling someone to find all the Cranecloud Medium articles via the CC Page and they can follow this link, followed by the link.
> 
> @MutegekiHenry thank you for the feedback let me work on that ASAP!


@MutegekiHenry this has been worked upon.

**Comment by MutegekiHenry** [comment]
> > > @neelxie Thanks for this. I prefer it when you have a small description under the Medium Articles heading and in there that's where the link can be put. Just a line telling someone to find all the Cranecloud Medium articles via the CC Page and they can follow this link, followed by the link.
> > 
> > 
> > @MutegekiHenry thank you for the feedback let me work on that ASAP!
> 
> @MutegekiHenry this has been worked upon.

Awesome work @neelxie

**Review by MutegekiHenry — APPROVED** [review]

**Review by Mubangizi — APPROVED** [review]
LGTM

**Pull request merged**
